### ISSUE TITLE
LinearScan.Contravariant missing?

### ISSUE THREAD

**Issue by Chobbes** [jwiegley/linearscan#2]
Hello! Trying to build linearscan for a project, and I get this problem with both cabal-install and stack:

```
Configuring linearscan-0.11...
Building linearscan-0.11...
Preprocessing library linearscan-0.11...

LinearScan/Const.hs:16:18:
    Could not find module ‘LinearScan.Contravariant’
    Use -v to see a list of the files searched for.
```

Do you know what might be happening? I have also tried going back to version 0.10.2, but I get the same problem as well. Thanks!

**Comment by jwiegley** [comment]
Thanks for this report, @Chobbes!  Somehow I'd missing that the Cabal file didn't reference that file.

I've uploaded release 0.11.1, which should build fine for you again.
